
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\Doctrine\Type\AbstractEnumType:
            tags: [ 'app.doctrine_enum_type' ]

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
